"""initial schema

Revision ID: fa194da18ea1
Revises:
Create Date: 2026-04-23 17:34:32.581441

"""

from __future__ import annotations

from collections.abc import Sequence

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "fa194da18ea1"
down_revision: str | Sequence[str] | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "llm_cache",
        sa.Column("cache_key", sa.String(length=128), nullable=False),
        sa.Column("input_hash", sa.String(length=128), nullable=False),
        sa.Column("prompt_version", sa.String(length=64), nullable=False),
        sa.Column("model", sa.String(length=128), nullable=False),
        sa.Column("temperature", sa.Float(), nullable=False),
        sa.Column("raw_output", sa.Text(), nullable=False),
        sa.Column("parsed_output", sa.JSON(), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.PrimaryKeyConstraint("cache_key"),
    )
    with op.batch_alter_table("llm_cache", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_llm_cache_input_hash"), ["input_hash"], unique=False)

    op.create_table(
        "mentions",
        sa.Column("mention_id", sa.String(length=128), nullable=False),
        sa.Column(
            "source_type",
            sa.Enum(
                "reddit_post",
                "reddit_comment",
                "bestbuy_review",
                "amazon_review",
                "youtube_chunk",
                "article",
                name="sourcetype",
                native_enum=False,
                length=32,
            ),
            nullable=False,
        ),
        sa.Column("source_url", sa.String(length=2048), nullable=False),
        sa.Column("published_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("author", sa.String(length=256), nullable=True),
        sa.Column("raw_text", sa.Text(), nullable=False),
        sa.Column("channel", sa.String(length=256), nullable=True),
        sa.Column("metadata", sa.JSON(), nullable=False),
        sa.Column("first_seen_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("tombstoned_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("tombstone_reason", sa.String(length=128), nullable=True),
        sa.PrimaryKeyConstraint("mention_id"),
    )
    op.create_table(
        "products",
        sa.Column("product_id", sa.String(length=128), nullable=False),
        sa.Column("display_name", sa.String(length=256), nullable=False),
        sa.Column("brand", sa.String(length=128), nullable=False),
        sa.Column("aliases", sa.JSON(), nullable=False),
        sa.Column("attribution_patterns", sa.JSON(), nullable=False),
        sa.Column("urls", sa.JSON(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.PrimaryKeyConstraint("product_id"),
    )
    op.create_table(
        "runs",
        sa.Column("run_id", sa.String(length=64), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("config_snapshot", sa.JSON(), nullable=False),
        sa.Column("taxonomy_version", sa.String(length=32), nullable=False),
        sa.Column("prompt_versions", sa.JSON(), nullable=False),
        sa.PrimaryKeyConstraint("run_id"),
    )
    op.create_table(
        "aggregates_aspect_sku",
        sa.Column("aggregate_id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("run_id", sa.String(length=64), nullable=False),
        sa.Column("product_id", sa.String(length=128), nullable=False),
        sa.Column(
            "aspect",
            sa.Enum(
                "thermals",
                "performance",
                "keyboard",
                "display",
                "battery",
                "build_quality",
                "software_experience",
                "price_value",
                "support_warranty",
                "aesthetics",
                "portability",
                name="aspect",
                native_enum=False,
                length=32,
            ),
            nullable=False,
        ),
        sa.Column("total_mentions", sa.Integer(), nullable=False),
        sa.Column("polarity_counts", sa.JSON(), nullable=False),
        sa.Column("net_sentiment", sa.Float(), nullable=False),
        sa.Column("intensity_counts", sa.JSON(), nullable=False),
        sa.Column("verified_share", sa.Float(), nullable=False),
        sa.Column("by_source", sa.JSON(), nullable=False),
        sa.Column("by_recency", sa.JSON(), nullable=False),
        sa.Column("mention_ids", sa.JSON(), nullable=False),
        sa.Column("computed_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(["product_id"], ["products.product_id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["run_id"], ["runs.run_id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("aggregate_id"),
        sa.UniqueConstraint("run_id", "product_id", "aspect", name="uq_aggregates_aspect_sku_key"),
    )
    with op.batch_alter_table("aggregates_aspect_sku", schema=None) as batch_op:
        batch_op.create_index(
            batch_op.f("ix_aggregates_aspect_sku_product_id"), ["product_id"], unique=False
        )
        batch_op.create_index(
            batch_op.f("ix_aggregates_aspect_sku_run_id"), ["run_id"], unique=False
        )

    op.create_table(
        "aggregates_pair_reason",
        sa.Column("aggregate_id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("run_id", sa.String(length=64), nullable=False),
        sa.Column("pair_id", sa.String(length=256), nullable=False),
        sa.Column("winning_product_id", sa.String(length=128), nullable=False),
        sa.Column(
            "reason_bucket",
            sa.Enum(
                "thermals",
                "performance",
                "keyboard",
                "display",
                "battery",
                "build_quality",
                "software_experience",
                "price_value",
                "support_warranty",
                "aesthetics",
                "portability",
                "brand_loyalty",
                "value_deal",
                "support_reputation",
                "prior_ownership",
                name="reasonbucket",
                native_enum=False,
                length=32,
            ),
            nullable=False,
        ),
        sa.Column("total_mentions", sa.Integer(), nullable=False),
        sa.Column("intensity_counts", sa.JSON(), nullable=False),
        sa.Column(
            "addressability",
            sa.Enum(
                "messaging",
                "software",
                "hardware",
                "pricing",
                "mixed",
                name="addressability",
                native_enum=False,
                length=16,
            ),
            nullable=False,
        ),
        sa.Column("addressability_rationale", sa.Text(), nullable=False),
        sa.Column("representative_mention_ids", sa.JSON(), nullable=False),
        sa.Column("mention_ids", sa.JSON(), nullable=False),
        sa.Column("computed_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(["run_id"], ["runs.run_id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(
            ["winning_product_id"], ["products.product_id"], ondelete="CASCADE"
        ),
        sa.PrimaryKeyConstraint("aggregate_id"),
        sa.UniqueConstraint(
            "run_id",
            "pair_id",
            "winning_product_id",
            "reason_bucket",
            name="uq_aggregates_pair_reason_key",
        ),
    )
    with op.batch_alter_table("aggregates_pair_reason", schema=None) as batch_op:
        batch_op.create_index(
            batch_op.f("ix_aggregates_pair_reason_pair_id"), ["pair_id"], unique=False
        )
        batch_op.create_index(
            batch_op.f("ix_aggregates_pair_reason_run_id"), ["run_id"], unique=False
        )
        batch_op.create_index(
            batch_op.f("ix_aggregates_pair_reason_winning_product_id"),
            ["winning_product_id"],
            unique=False,
        )

    op.create_table(
        "aspect_tags",
        sa.Column("tag_id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("mention_id", sa.String(length=128), nullable=False),
        sa.Column("product_id", sa.String(length=128), nullable=False),
        sa.Column(
            "aspect",
            sa.Enum(
                "thermals",
                "performance",
                "keyboard",
                "display",
                "battery",
                "build_quality",
                "software_experience",
                "price_value",
                "support_warranty",
                "aesthetics",
                "portability",
                name="aspect",
                native_enum=False,
                length=32,
            ),
            nullable=False,
        ),
        sa.Column(
            "polarity",
            sa.Enum(
                "negative", "neutral", "positive", name="polarity", native_enum=False, length=16
            ),
            nullable=False,
        ),
        sa.Column(
            "intensity",
            sa.Enum("low", "medium", "high", name="intensity", native_enum=False, length=16),
            nullable=False,
        ),
        sa.Column("classifier_confidence", sa.Float(), nullable=True),
        sa.Column("taxonomy_version", sa.String(length=32), nullable=False),
        sa.Column("prompt_version", sa.String(length=64), nullable=False),
        sa.Column("model", sa.String(length=128), nullable=False),
        sa.Column("temperature", sa.Float(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(["mention_id"], ["mentions.mention_id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["product_id"], ["products.product_id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("tag_id"),
        sa.UniqueConstraint(
            "mention_id",
            "product_id",
            "aspect",
            "taxonomy_version",
            "prompt_version",
            name="uq_aspect_tags_key",
        ),
    )
    with op.batch_alter_table("aspect_tags", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_aspect_tags_mention_id"), ["mention_id"], unique=False)
        batch_op.create_index(batch_op.f("ix_aspect_tags_product_id"), ["product_id"], unique=False)

    op.create_table(
        "briefs",
        sa.Column("brief_id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("run_id", sa.String(length=64), nullable=False),
        sa.Column(
            "scope_type",
            sa.Enum(
                "aspect_1_sku", "aspect_2_pair", name="scopetype", native_enum=False, length=16
            ),
            nullable=False,
        ),
        sa.Column("scope_id", sa.String(length=256), nullable=False),
        sa.Column("narrative", sa.JSON(), nullable=False),
        sa.Column("generated_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("prompt_version", sa.String(length=64), nullable=False),
        sa.Column("model", sa.String(length=128), nullable=False),
        sa.ForeignKeyConstraint(["run_id"], ["runs.run_id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("brief_id"),
    )
    with op.batch_alter_table("briefs", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_briefs_run_id"), ["run_id"], unique=False)
        batch_op.create_index(batch_op.f("ix_briefs_scope_id"), ["scope_id"], unique=False)

    op.create_table(
        "deliberation_tags",
        sa.Column("tag_id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("thread_mention_id", sa.String(length=128), nullable=False),
        sa.Column("is_deliberation", sa.Boolean(), nullable=False),
        sa.Column("is_resolved", sa.Boolean(), nullable=False),
        sa.Column("products_discussed", sa.JSON(), nullable=False),
        sa.Column("chosen_product_id", sa.String(length=128), nullable=True),
        sa.Column("prompt_version", sa.String(length=64), nullable=False),
        sa.Column("model", sa.String(length=128), nullable=False),
        sa.Column("temperature", sa.Float(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(
            ["chosen_product_id"], ["products.product_id"], ondelete="SET NULL"
        ),
        sa.ForeignKeyConstraint(["thread_mention_id"], ["mentions.mention_id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("tag_id"),
    )
    with op.batch_alter_table("deliberation_tags", schema=None) as batch_op:
        batch_op.create_index(
            batch_op.f("ix_deliberation_tags_thread_mention_id"),
            ["thread_mention_id"],
            unique=False,
        )

    op.create_table(
        "mention_attributions",
        sa.Column("attribution_id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("mention_id", sa.String(length=128), nullable=False),
        sa.Column("product_id", sa.String(length=128), nullable=False),
        sa.Column(
            "attribution_type",
            sa.Enum("primary", "secondary", name="attributiontype", native_enum=False, length=16),
            nullable=False,
        ),
        sa.Column(
            "attribution_method",
            sa.Enum("regex", "url", name="attributionmethod", native_enum=False, length=16),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(["mention_id"], ["mentions.mention_id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["product_id"], ["products.product_id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("attribution_id"),
        sa.UniqueConstraint(
            "mention_id", "product_id", "attribution_type", name="uq_mention_attributions_key"
        ),
    )
    with op.batch_alter_table("mention_attributions", schema=None) as batch_op:
        batch_op.create_index(
            batch_op.f("ix_mention_attributions_mention_id"), ["mention_id"], unique=False
        )
        batch_op.create_index(
            batch_op.f("ix_mention_attributions_product_id"), ["product_id"], unique=False
        )

    op.create_table(
        "pair_win_rates",
        sa.Column("aggregate_id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("run_id", sa.String(length=64), nullable=False),
        sa.Column("pair_id", sa.String(length=256), nullable=False),
        sa.Column("product_a_id", sa.String(length=128), nullable=False),
        sa.Column("product_b_id", sa.String(length=128), nullable=False),
        sa.Column("total_resolved_threads", sa.Integer(), nullable=False),
        sa.Column("a_wins", sa.Integer(), nullable=False),
        sa.Column("b_wins", sa.Integer(), nullable=False),
        sa.Column("ties", sa.Integer(), nullable=False),
        sa.Column("thread_mention_ids", sa.JSON(), nullable=False),
        sa.Column("computed_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(["product_a_id"], ["products.product_id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["product_b_id"], ["products.product_id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["run_id"], ["runs.run_id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("aggregate_id"),
        sa.UniqueConstraint("run_id", "pair_id", name="uq_pair_win_rates_key"),
    )
    with op.batch_alter_table("pair_win_rates", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_pair_win_rates_pair_id"), ["pair_id"], unique=False)
        batch_op.create_index(batch_op.f("ix_pair_win_rates_run_id"), ["run_id"], unique=False)

    op.create_table(
        "reason_tags",
        sa.Column("tag_id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("mention_id", sa.String(length=128), nullable=False),
        sa.Column("thread_mention_id", sa.String(length=128), nullable=False),
        sa.Column("winning_product_id", sa.String(length=128), nullable=False),
        sa.Column(
            "reason_bucket",
            sa.Enum(
                "thermals",
                "performance",
                "keyboard",
                "display",
                "battery",
                "build_quality",
                "software_experience",
                "price_value",
                "support_warranty",
                "aesthetics",
                "portability",
                "brand_loyalty",
                "value_deal",
                "support_reputation",
                "prior_ownership",
                name="reasonbucket",
                native_enum=False,
                length=32,
            ),
            nullable=False,
        ),
        sa.Column(
            "polarity",
            sa.Enum(
                "negative", "neutral", "positive", name="polarity", native_enum=False, length=16
            ),
            nullable=False,
        ),
        sa.Column(
            "intensity",
            sa.Enum("low", "medium", "high", name="intensity", native_enum=False, length=16),
            nullable=False,
        ),
        sa.Column("prompt_version", sa.String(length=64), nullable=False),
        sa.Column("model", sa.String(length=128), nullable=False),
        sa.Column("temperature", sa.Float(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(["mention_id"], ["mentions.mention_id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["thread_mention_id"], ["mentions.mention_id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(
            ["winning_product_id"], ["products.product_id"], ondelete="CASCADE"
        ),
        sa.PrimaryKeyConstraint("tag_id"),
    )
    with op.batch_alter_table("reason_tags", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_reason_tags_mention_id"), ["mention_id"], unique=False)
        batch_op.create_index(
            batch_op.f("ix_reason_tags_thread_mention_id"), ["thread_mention_id"], unique=False
        )
        batch_op.create_index(
            batch_op.f("ix_reason_tags_winning_product_id"), ["winning_product_id"], unique=False
        )

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("reason_tags", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_reason_tags_winning_product_id"))
        batch_op.drop_index(batch_op.f("ix_reason_tags_thread_mention_id"))
        batch_op.drop_index(batch_op.f("ix_reason_tags_mention_id"))

    op.drop_table("reason_tags")
    with op.batch_alter_table("pair_win_rates", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_pair_win_rates_run_id"))
        batch_op.drop_index(batch_op.f("ix_pair_win_rates_pair_id"))

    op.drop_table("pair_win_rates")
    with op.batch_alter_table("mention_attributions", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_mention_attributions_product_id"))
        batch_op.drop_index(batch_op.f("ix_mention_attributions_mention_id"))

    op.drop_table("mention_attributions")
    with op.batch_alter_table("deliberation_tags", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_deliberation_tags_thread_mention_id"))

    op.drop_table("deliberation_tags")
    with op.batch_alter_table("briefs", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_briefs_scope_id"))
        batch_op.drop_index(batch_op.f("ix_briefs_run_id"))

    op.drop_table("briefs")
    with op.batch_alter_table("aspect_tags", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_aspect_tags_product_id"))
        batch_op.drop_index(batch_op.f("ix_aspect_tags_mention_id"))

    op.drop_table("aspect_tags")
    with op.batch_alter_table("aggregates_pair_reason", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_aggregates_pair_reason_winning_product_id"))
        batch_op.drop_index(batch_op.f("ix_aggregates_pair_reason_run_id"))
        batch_op.drop_index(batch_op.f("ix_aggregates_pair_reason_pair_id"))

    op.drop_table("aggregates_pair_reason")
    with op.batch_alter_table("aggregates_aspect_sku", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_aggregates_aspect_sku_run_id"))
        batch_op.drop_index(batch_op.f("ix_aggregates_aspect_sku_product_id"))

    op.drop_table("aggregates_aspect_sku")
    op.drop_table("runs")
    op.drop_table("products")
    op.drop_table("mentions")
    with op.batch_alter_table("llm_cache", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_llm_cache_input_hash"))

    op.drop_table("llm_cache")
    # ### end Alembic commands ###
